trigger:
- main   # or your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Build & Push Docker Image to Docker Hub
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'DockerHubServiceConnection'
    repository: 'nsbyadav14e/flip01'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

# Step 2: Deploy to Azure Web App (Container)
- task: AzureWebAppContainer@1
  displayName: Deploy Docker image to Azure Web App
  inputs:
    azureSubscription: 'AzureServiceConnection'
    appName: 'sivaapp01234'
    containers: 'nsbyadav14e/flip01:latest'
